# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# remap prefix for 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-f
bind-key C-f send-prefix

# reload config file with r 
bind r source-file ~/.tmux.conf

# split panes using h and v
bind h split-window -h
bind v split-window -v
unbind '"'
unbind $

# switch panes using Alt-arrow without prefix
bind-key -n C-h select-pane -L
bind-key -n C-l select-pane -R
bind-key -n C-j select-pane -U
bind-key -n C-k select-pane -D

# remove close pane check
bind-key x kill-pane

# remove delay switching vim mode
set -sg escape-time 0
# Enable mouse mode (tmux 2.1 and above)
set -g mouse on

# List of plugins
# set -g @plugin 'tmux-plugins/tpm'
# set -g @plugin 'dracula/tmux'
# set -g @dracula-plugins "spotify-tui cpu-usage ram-usage time"
# set -g @dracula-show-timezone false

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
# run '~/.tmux/plugins/tpm/tpm'
# tmux set-option status-style fg=white,bg=black

set -g status-style 'fg=white'
set -g status-style 'bg=black'
set -g status-position bottom
set -g status-justify left
set -g status-right '%Y-%m-%d %H:%M '
set -g status-right-length 50
set -g status-left ' '
